/**
 * Romane Zimmermann
 * Projet Démineur
 */

package cpo_miniprojet_zimmermann;

import javax.swing.*;
import java.awt.event.ActionListener;

public class FenetrePrincipale extends javax.swing.JFrame {

    private GrilleDeJeu grille; // Grille de jeu
    private int nbCoups;        // Nombre de coups

    public FenetrePrincipale(Partie partie) {
        this.grille = partie.getGrille();
        this.nbCoups = 0;

        initComponents(); // Appel après avoir défini grille
        initialiserGrilleGraphique();
        
        // Redimensionner la fenêtre pour qu'elle soit plus grande
        setSize(600, 600); // Ajuster la taille de la fenêtre
        //jPanel1.setLayout(null); // Utilisation de null layout pour positionnement absolu
    }
    private void mettreAJourGrilleGraphique() {

    for (int i = 0; i < grille.getNbLignes(); i++) {
        for (int j = 0; j < grille.getNbColonnes(); j++) {
            Cellule cellule = grille.matriceCellules[i][j];
            Cellule_Graphique bouton = (Cellule_Graphique) jPanel1.getComponent(i * grille.getNbColonnes() + j);

            if (cellule.estDevoilee()) {
                if (cellule.getPresenceBombe()) {
                    bouton.setText("💣");
                } else {
                    bouton.setText(String.valueOf(cellule.getNbBombesAdjacentes()));
                }
            } else {
                bouton.setText("");
            }
        }
    }
}


    private void initialiserGrilleGraphique() {
            jPanel1.setLayout(new java.awt.GridLayout(grille.getNbLignes(), grille.getNbColonnes()));

        for (int i = 0; i < grille.getNbLignes(); i++) {
            for (int j = 0; j < grille.getNbColonnes(); j++) {
                Cellule_Graphique bouton = new Cellule_Graphique(i, j, grille.matriceCellules[i][j]);
                bouton.addActionListener(creerActionListener(bouton));

                jPanel1.add(bouton); // Ajouter chaque bouton à jPanel1
            }
        }
    }

    private ActionListener creerActionListener(Cellule_Graphique bouton) {
    return e -> {
        int ligne = bouton.x;
        int colonne = bouton.y;

        Cellule cellule = grille.matriceCellules[ligne][colonne];

        if (!cellule.estDevoilee()) {
            if (cellule.getPresenceBombe()) {
                // Bombe cliquée : afficher un message de défaite
                bouton.setText("💣");
                JOptionPane.showMessageDialog(this, "BOUM ! Game Over !");
                System.exit(0);
            } else {
                // Révéler les cellules (logique)
                grille.revelerCelluleParCoordonnees(ligne, colonne);

                // Mettre à jour l'interface graphique
                mettreAJourGrilleGraphique();

                // Vérifier si toutes les cellules non-bombes sont dévoilées
                if (grille.toutesCellulesRevelees()) {
                    JOptionPane.showMessageDialog(this, "Félicitations, vous avez gagné !");
                    System.exit(0);
                }
            }
        }
    };
}



    private void verifierEtatPartie() {
        if (grille.toutesCellulesRevelees()) {
            JOptionPane.showMessageDialog(this, "Félicitations, vous avez gagné !");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RECOMMENCER = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new java.awt.GridLayout(4, 4));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 420, 360));

        RECOMMENCER.setText("RECOMMENCER");
        RECOMMENCER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RECOMMENCERActionPerformed(evt);
            }
        });
        getContentPane().add(RECOMMENCER, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("BUT DU JEU : trouver toutes les cases sans tomber sur les bombes  ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 410, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("le nombre dans la case indique le nombre de bombes qui se trouvent autour de cette case");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel5.setText("⭐");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 30, 40));

        jLabel6.setText("⭐");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 20, 20));

        jLabel7.setText("⭐");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 30, 40));

        jLabel8.setText("⭐");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 40));

        jLabel9.setText("⭐");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 30, 40));

        jLabel10.setText("⭐");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 30, 40));

        jLabel1.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 18)); // NOI18N
        jLabel1.setText("JEU ROMZI STAR ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -30, 420, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RECOMMENCERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RECOMMENCERActionPerformed
                                                                                    
    grille.reinitialiserBombes();
    jPanel1.removeAll();
    initialiserGrilleGraphique();
    jPanel1.revalidate();
    jPanel1.repaint();
      
        // TODO add your handling code here:
    }//GEN-LAST:event_RECOMMENCERActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            Partie partie = new Partie(10, 10, 10); // Exemple avec une grille 5x5 et 5 bombes
            new FenetrePrincipale(partie).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RECOMMENCER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
